language: csharp
dist: trusty
sudo: required
solution: EncryptionMethods.sln
mono: none
dotnet: 2.1.4

install:
  - dotnet restore EncryptionMethods.sln

script:
- dotnet build EncryptionMethods.sln
- dotnet test ./Polyalphabetic.Tests/Polyalphabetic.Tests.csproj