language: csharp
dist: xenial
sudo: required
solution: EncryptionMethods.sln
mono: none
dotnet: 5.0

install:
  - dotnet restore EncryptionMethods.sln

script:
- dotnet --info
- dotnet build EncryptionMethods.sln
- dotnet test ./Polyalphabetic/Polyalphabetic.Tests/Polyalphabetic.Tests.csproj
- dotnet test ./DSA/DSA.Tests/DSA.Tests.csproj
- dotnet test ./MD5/MD5.Tests/MD5.Tests.csproj